CMDB/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('manage/',include('manage.urls')),
    path('assets/', include('assets.urls')),
    path('baseline/',include('baseline.urls')),
    path('',include('assets.urls'))
]

baseline/urls.py
from django.urls import path
from baseline import views

app_name = 'baseline'


urlpatterns = [
    # path('report/', views.report, name='report'),
    path('linux_scan_res_report/', views.linux_scan_res_report, name="linux_scan_res_report"),
    path('windows_scan_res_report/', views.windows_scan_res_report, name="windows_scan_res_report"),    
    path('scan_res_display/',views.scan_res_display,name="scan_res_display"),
    path('os_check_res_display/',views.os_check_res_display,name="os_check_res_display"),
    path('middlware_check_res_display/',views.middleware_check_res_display,name="middleware_check_res_display"),
    path('vuln_check_res_display/',views.vuln_check_res_display,name="vuln_check_res_display"),
    path('check_choice/',views.check_choice,name="check_choice"),
    path('test/',views.linux_vuln_check_res_store,name="test")
]

baseline/models.py
from django.db import models


# Create your models here.
class AllScanResRecord(models.Model):
    scanTime=models.DateTimeField(verbose_name="scanTime")
    scanType=models.CharField(max_length=50,verbose_name="scanTime")
    hostname=models.CharField(max_length=100,verbose_name="hostname")
    osVersion=models.CharField(max_length=100,verbose_name="osVersion")
    ipList=models.CharField(max_length=200,verbose_name="ipList")
    macaddr=models.CharField(max_length=500,verbose_name="macaddr")
    def __str__(self):
        return '%s %s' %(self.scanTime,self.macaddr)
    class Meta:
        verbose_name="所有安全基线的扫描记录"
        verbose_name_plural="所有安全基线的扫描记录"
class WindowsCheckRes(models.Model):
    # basic_info
    scanTime=models.DateTimeField(verbose_name="scanTime")
    hostname=models.CharField(max_length=100,verbose_name="hostname")
    osVersion=models.CharField(max_length=100,verbose_name="osVersion")
    ipList=models.CharField(max_length=200,verbose_name="ipList")
    macaddr=models.CharField(max_length=500,verbose_name="macaddr")

    # account_check_res
    ## password_check_info
    passwordHistorySize=models.CharField(max_length=20,default="False",verbose_name="passwordHistorySize")
    maximumPasswordAge=models.CharField(max_length=20,default="False",verbose_name="maximumPasswordAge")
    minimumPasswordAge=models.CharField(max_length=20,default="False",verbose_name="minimumPasswordAge")
    passwordComplexity=models.CharField(max_length=20,default="False",verbose_name="passwordComplexity")
    clearTextPassword=models.CharField(max_length=20,default="False",verbose_name="clearTextPassword")
    minimumPasswordLength=models.CharField(max_length=20,default="False",verbose_name="minimumPasswordLength")
    ## account_lockout_info
    lockoutDuration=models.CharField(max_length=20,default="False",verbose_name="lockoutDuration")
    lockoutBadCount=models.CharField(max_length=20,default="False",verbose_name="lockoutBadCount")
    resetLockoutCount=models.CharField(max_length=20,default="False",verbose_name="resetLockoutCount")

    # audit_check_res
    auditPolicyChange=models.CharField(max_length=20,default="False",verbose_name="auditPolicyChange")
    auditLogonEvents=models.CharField(max_length=20,default="False",verbose_name="auditLogonEvents")
    auditObjectAccess=models.CharField(max_length=20,default="False",verbose_name="auditObjectAccess")
    auditProcessTracking=models.CharField(max_length=20,default="False",verbose_name="auditProcessTracking")
    auditDSAccess=models.CharField(max_length=20,default="False",verbose_name="auditDSAccess")
    auditSystemEvents=models.CharField(max_length=20,default="False",verbose_name="auditSystemEvents")
    auditAccountLogon=models.CharField(max_length=20,default="False",verbose_name="auditAccontLogon")
    auditAccountManage=models.CharField(max_length=20,default="False",verbose_name="auditAccountManage")

    # userright_check_res
    seTrustedCredManAccessPrivilegeIFNone=models.CharField(max_length=20,default="False",verbose_name="seTrustedCredManAccessPrivilegeIFNone")
    seTcbPrivilegeIFNone=models.CharField(max_length=20,default="False",verbose_name="seTcbPrivilegeIFNone")
    seMachineAccountPrivilegeIFOnlySpecifiedUserOrArray=models.CharField(max_length=20,default="False",verbose_name="seMachineAccountPrivilegeIFOnlySpecifiedUserOrArray")
    seCreateGlobalPrivilegeIFNone=models.CharField(max_length=20,default="False",verbose_name="seCreateGlobalPrivilegeIFNone")
    seDenyBatchLogonRightIFContainGuests=models.CharField(max_length=20,default="False",verbose_name="seDenyBatchLogonRightIFContainGuests")
    seDenyServiceLogonRightIFContainGuests=models.CharField(max_length=20,default="False",verbose_name="seDenyServiceLogonRightIFContainGuests")
    seDenyInteractiveLogonRightIFContainGuests=models.CharField(max_length=20,default="False",verbose_name="seDenyInteractiveLogonRightIFContainGuests")
    seRemoteShutdownPrivilegeIFOnlySpecifiedUserOrArray=models.CharField(max_length=20,default="False",verbose_name="seRemoteShutdownPrivilegeIFOnlySpecifiedUserOrArray")
    seRelabelPrivilegeIFNone=models.CharField(max_length=20,default="False",verbose_name="seRelabelPrivilegeIFNone")
    seSyncAgentPrivilegeIFNone=models.CharField(max_length=20,default="False",verbose_name="seSyncAgentPrivilegeIFNone")

    # secureoption_check_res
    enableGuestAccount=models.CharField(max_length=20,default="False",verbose_name="enableGuestAccount")
    limitBlankPasswordUse=models.CharField(max_length=20,default="False",verbose_name="limitBlankPasswordUse")
    newAdministratorName=models.CharField(max_length=20,default="False",verbose_name="newAdministratorName")
    newGuestName=models.CharField(max_length=20,default="False",verbose_name="newGuestName")
    dontDisplayLastUserName=models.CharField(max_length=20,default="False",verbose_name="dontDisplayLastUserName")
    disableCAD=models.CharField(max_length=20,default="False",verbose_name="disableCAD")
    inactivityTimeoutSecs=models.CharField(max_length=20,default="False",verbose_name="inactivityTimeoutSecs")
    enablePlainTextPassword=models.CharField(max_length=20,default="False",verbose_name="enablePlainTextPassword")
    autoDisconnect=models.CharField(max_length=20,default="False",verbose_name="autoDisconnect")
    noLMHash=models.CharField(max_length=20,default="False",verbose_name="noLMHash")
    lsaAnonymousNameLookup=models.CharField(max_length=20,default="False",verbose_name="lsaAnonymousNameLookup")
    restrictAnonymousSAM=models.CharField(max_length=20,default="False",verbose_name="restrictAnonymousSAM")
    restrictAnonymous=models.CharField(max_length=20,default="False",verbose_name="restrictAnonymous")
    clearPageFileAtShutdown=models.CharField(max_length=20,default="False",verbose_name="clearPageFileAtShutdown")

    # portsecure_check_res
    rdpPort=models.CharField(max_length=20,default="False",verbose_name="rdpPort")

    # systemsecure_check_res
    autoRunRes=models.CharField(max_length=20,default="False",verbose_name="autoRunRes")
    def __str__(self):
        return '%s %s'%(self.scanTime,self.macaddr)
    class Meta:
        verbose_name="Windows安全基线检查结果"
        verbose_name="windows安全基线检查结果"
class WindowsScanResMeta(models.Model):
    # 时间
    scanTime=models.DateTimeField(verbose_name="scanTime")
    # macaddr
    macaddr=models.CharField(max_length=500,verbose_name="macaddr")
    # 扫描结果
    windowsScanResMetaData=models.CharField(max_length=100000,verbose_name="windowsScanResMeta")
    def __str__(self):
        return '%s %s'%(self.scanTime,self.macaddr)
    class Meta:
        verbose_name="windows安全基线扫描结果元数据"
        verbose_name_plural="Windows安全基线扫描结果元数据"

class WindowsScanRes(models.Model):
    # basic_info
    scanTime=models.DateTimeField(verbose_name="scanTime")
    hostname=models.CharField(max_length=100,verbose_name="hostname")
    osVersion=models.CharField(max_length=100,verbose_name="osVersion")
    ipList=models.CharField(max_length=200,verbose_name="ipList")
    macaddr=models.CharField(max_length=500,verbose_name="macaddr")

    # account_check_res
    ## password_check_info
    passwordHistorySize=models.IntegerField(verbose_name="passwordHistorySize")
    maximumPasswordAge=models.IntegerField(verbose_name="maximumPasswordAge")
    minimumPasswordAge=models.IntegerField(verbose_name="minimumPasswordAge")
    passwordComplexity=models.IntegerField(verbose_name="passwordComplexity")
    clearTextPassword=models.IntegerField(verbose_name="clearTextPassword")
    minimumPasswordLength=models.IntegerField(verbose_name="minimumPasswordLength")
    ## account_lockout_info
    lockoutDuration=models.IntegerField(verbose_name="lockoutDuration")
    lockoutBadCount=models.IntegerField(verbose_name="lockoutBadCount")
    resetLockoutCount=models.IntegerField(verbose_name="resetLockoutCount")

    # audit_check_res
    auditPolicyChange=models.IntegerField(verbose_name="auditPolicyChange")
    auditLogonEvents=models.IntegerField(verbose_name="auditLogonEvents")
    auditObjectAccess=models.IntegerField(verbose_name="auditObjectAccess")
    auditProcessTracking=models.IntegerField(verbose_name="auditProcessTracking")
    auditDSAccess=models.IntegerField(verbose_name="auditDSAccess")
    auditSystemEvents=models.IntegerField(verbose_name="auditSystemEvents")
    auditAccountLogon=models.IntegerField(verbose_name="auditAccontLogon")
    auditAccountManage=models.IntegerField(verbose_name="auditAccountManage")

    # userright_check_res
    seTrustedCredManAccessPrivilegeIFNone=models.CharField(max_length=100,verbose_name="seTrustedCredManAccessPrivilegeIFNone")
    seTcbPrivilegeIFNone=models.CharField(max_length=100,verbose_name="seTcbPrivilegeIFNone")
    seMachineAccountPrivilegeIFOnlySpecifiedUserOrArray=models.CharField(max_length=100,verbose_name="seMachineAccountPrivilegeIFOnlySpecifiedUserOrArray")
    seCreateGlobalPrivilegeIFNone=models.CharField(max_length=100,verbose_name="seCreateGlobalPrivilegeIFNone")
    seDenyBatchLogonRightIFContainGuests=models.BooleanField(verbose_name="seDenyBatchLogonRightIFContainGuests")
    seDenyServiceLogonRightIFContainGuests=models.BooleanField(verbose_name="seDenyServiceLogonRightIFContainGuests")
    seDenyInteractiveLogonRightIFContainGuests=models.BooleanField(verbose_name="seDenyInteractiveLogonRightIFContainGuests")
    seRemoteShutdownPrivilegeIFOnlySpecifiedUserOrArray=models.CharField(max_length=100,verbose_name="seRemoteShutdownPrivilegeIFOnlySpecifiedUserOrArray")
    seRelabelPrivilegeIFNone=models.CharField(max_length=100,verbose_name="seRelabelPrivilegeIFNone")
    seSyncAgentPrivilegeIFNone=models.CharField(max_length=100,verbose_name="seSyncAgentPrivilegeIFNone")

    # secureoption_check_res
    enableGuestAccount=models.BooleanField(verbose_name="enableGuestAccount")
    limitBlankPasswordUse=models.BooleanField(verbose_name="limitBlankPasswordUse")

baseline/templates/baseline/check_choice_res_display.html
{% extends 'base.html'%}
{% load static%}
{% load base64_jc %}

{% block title %}基线检查记录{% endblock %}
{% block css %}
     <link rel="stylesheet" href="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
<style>
.jc-red-badge{
  display: inline-block;
    min-width: 10px;
    padding: 3px 7px;
    font-size: 12px;
    font-weight: 700;
    line-height: 1;
    color: #fff;
    text-align: center;
    white-space: nowrap;
    vertical-align: middle !important;
    background-color:red;
    border-radius: 10px;
}
/* td{
  word-break:break-all;
  vertical-align: middle!important;
} */
table{
	table-layout:fixed;
}	
td{
    overflow:hidden;
    white-space:nowrap;
    text-overflow:ellipsis;
}
</style>
{% endblock %}
{% block content %}

    <div class="box">

      <div class="box-header with-border">

         <h3 class="box-title">基础信息</h3>

         <div class="box-tools pull-right">
           <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
             <i class="fa fa-minus"></i></button>
           <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
             <i class="fa fa-times"></i></button>
         </div>
       </div>
       <div class="box-body">
         <table class="table table-bordered table-striped dataTable">
           <tr>
             <td>扫描时间:{{scanTime}}</td>
             <td>项目类型:{{scanType}}</td>
           </tr>
           <tr>
             <td>主机名:{{scanRes.hostname}}</td>
             <td>系统版本:{{osVersion }}</td>
           </tr>
           <tr>
             <td>MAC地址:{{macaddr}}</td>
             <td>IP地址:{{scanRes.ipList}}</td>
           </tr>
         </table>
       </div>
    </div>


<div>
  <!-- Nav tabs -->
  <ul id="mytab" class="nav nav-pills nav-justified" role="tablist">
    <li role="presentation" class="active"><a href="#osCheckResult" aria-controls="home" role="tab" data-toggle="tab">系统基线检查</a></li>
    <li role="presentation"><a href="#middlewareCheckResult" aria-controls="profile" role="tab" data-toggle="tab">中间件基线检查</a></li>
    <li role="presentation"><a href="#databaseCheckResult" aria-controls="messages" role="tab" data-toggle="tab">数据库基线检查</a></li>
    <li role="presentation"><a href="#vulnCheckResult" aria-controls="test" role="tab" data-toggle="tab">主机漏洞信息</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="osCheckResult">os</div>
    <div role="tabpanel" class="tab-pane" id="middlewareCheckResult">middleware</div>
    <div role="tabpanel" class="tab-pane" id="databaseCheckResult">开发中</div>
    <div role="tabpanel" class="tab-pane" id="vulnCheckResult"></div>
  </div>

</div>

{% endblock %}
{% block script %}
<script src="{% static 'adminlet-2.4.10/bower_components/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'adminlet-2.4.10/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- <script src="{% static 'adminlet-2.4.10/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script> -->
<script>
    $("#osCheckResult").load('{% url "baseline:os_check_res_display" %}?scanType={{scanType|base64:"encode"}}&osVersion={{ osVersion|base64:"encode" }}&macaddr={{ macaddr|base64:"encode" }}&scanTime={{ scanTime|base64:"encode"}}')
    $('#mytab a').click(function(e){
        e.preventDefault()
        // $(this).tab('show')
        $("#osCheckResult").load('{% url "baseline:os_check_res_display" %}?scanType={{scanType|base64:"encode"}}&osVersion={{ osVersion|base64:"encode" }}&macaddr={{ macaddr|base64:"encode" }}&scanTime={{ scanTime|base64:"encode"}}')
        $("#middlewareCheckResult").load('{% url "baseline:middleware_check_res_display" %}?scanType={{scanType|base64:"encode"}}&osVersion={{ osVersion|base64:"encode" }}&macaddr={{ macaddr|base64:"encode" }}&scanTime={{ scanTime|base64:"encode"}}')
        $("#vulnCheckResult").load('{% url "baseline:vuln_check_res_display" %}?scanType={{scanType|base64:"encode"}}&osVersion={{ osVersion|base64:"encode" }}&macaddr={{ macaddr|base64:"encode" }}&scanTime={{ scanTime|base64:"encode"}}')
        $(this).tab('show')
    })
</script>
{% endblock %}

baseline/templates/baseline/linux_vuln_check_res_display.html
{% extends 'base_JC.html'%}
{% load static%}
{% load base64_jc %}

{% block title %}基线检查记录{% endblock %}
{% block css %}
     <link rel="stylesheet" href="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
<style>
.jc-red-badge{
  display: inline-block;
    min-width: 10px;
    padding: 3px 7px;
    font-size: 12px;
    font-weight: 700;
    line-height: 1;
    color: #fff;
    text-align: center;
    white-space: nowrap;
    vertical-align: middle !important;
    background-color:red;
    border-radius: 10px;
}
/* td{
  word-break:break-all;
  vertical-align: middle!important;
} */
table{
	table-layout:fixed;
}	
td{
    overflow:hidden;
    white-space:nowrap;
    text-overflow:ellipsis;
}
</style>
{% endblock %}
{% block content %}
   <!-- Main content -->
   <section class="content">

     <!-- 检查结果 -->
       <div class="box">
         <div class="box-header">
           <h3 class="box-title">检查结果</h3>
         </div>
         <div class="box-body">
          <table id="exp_table" class="table table-bordered table-striped dataTable">
            <thead>
              <tr>
                <th style="width:15%">product</th>
                <th style="width:15%">CVE</th>
                <th style="width:15%">Score</th>
                <th style="width:15%">EXP-info</th>
                <th style="width:40%">EXP-addr</th>
              </tr>
            </thead>
            <tbody>
              {% for checkResDict in vulnCheckResList%}
                {% for cveDict in checkResDict.cve %}
                  {% for exp in cveDict.exp %}
                  
              <tr>
                <td>{{checkResDict.product}}</td>
                <td>{{cveDict.CVEID}}</td>
                <td>{{cveDict.CVEScore}}</td>
                <td>{{exp.edb}}</td>
                <td>{{exp.desc}}</td>
              </tr>
              {% endfor %}
              {% endfor %}
              {% endfor%}
            </tbody>
          </table>
        </div>
       </div>
   </section>
{% endblock %}
{% block script %}
<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
<script>
$(function () {
        $('#exp_table').DataTable({
          "paging": true,       <!-- 允许分页 -->
          "lengthChange": true, <!-- 允许改变每页显示的行数 -->
          "searching": true,    <!-- 允许内容搜索 -->
          "ordering": true,     <!-- 允许排序 -->
          "info": true,         <!-- 显示信息 -->
          "autoWidth": false    <!-- 固定宽度 -->
        });
      });

</script>
{% endblock %}

baseline/templates/baseline/scan_res_display.html
{% extends 'base.html'%}
{% load static%}
{% load base64_jc %}
{% block title %}基线检查记录{% endblock %}
{% block css %}
     <link rel="stylesheet" href="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
{% endblock %}
{% block breadcrumb %}
<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        基线扫描结果
        <small>dashboard</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li class="active">基线扫描结果</li>
      </ol>
    </section>
{% endblock%}
{% block content %}
   <!-- Main content -->
   <section class="content">
     <div class="row">
       <div class="col-xs-12">

       <div class="box">
       <div class="box-header">
         <h3 class="box-title">基线检查<small>(系统)</small></h3>
       </div>
       <!-- /.box-header -->
       <div class="box-body">

           <table id="assets_table" class="table table-bordered table-striped">
               <thead>
                   <tr>
                       <th>序号</th>
                       <th>扫描时间</th>
                       <th>扫描类型</th>
                       <th>操作系统</th>
                       <th>服务器名称</th>
                       <th>IP信息</th>
                       <th>MAC地址</th>
                       <th>Result</th>
                   </tr>
               </thead>
               <tbody>
                    {% for scanRes in scanResAll %}
                    <tr>
                       <!-- 序号-->
                       <td>{{ forloop.counter }}</td>
                       <!-- 扫描时间-->
                       <td>{{ scanRes.scanTime }}</td>
                       <td>{{ scanRes.scanType}}</td>
                       <!-- 操作系统-->
                       <td>{{ scanRes.osVersion }}</td>
                       <!-- 服务器名称-->
                       <td>{{ scanRes.hostname }}</td>
                       <!-- IP信息 -->
                       <td>{{ scanRes.ipList }}</td>
                       <!-- MAC地址-->
                       <td>{{ scanRes.macaddr }}</td>
                       <td><a href='{% url "baseline:check_choice" %}?scanType={{scanRes.scanType|base64:"encode"}}&osVersion={{ scanRes.osVersion|base64:"encode" }}&macaddr={{ scanRes.macaddr|base64:"encode" }}&scanTime={{ scanRes.scanTime|base64:"encode"}}'>Click Me</a></td>
                    </tr>
                    {% empty %}
                    <tr>没有数据</tr>
                    {% endfor %}
               </tbody>
               <tfoot>
                   <tr>
                       <th>序号</th>
                       <th>扫描时间</th>
                       <th>扫描类型</th>
                       <th>操作系统</th>
                       <th>服务器名称</th>
                       <th>IP信息</th>
                       <th>MAC地址</th>
                       <th>Result</th>
                   </tr>
               </tfoot>
           </table>
       </div>
       <!-- /.box-body -->
     </div>
     <!-- /.box -->
       </div>
   <!-- /.col -->
     </div>
   <!-- /.row -->
   </section>
{% endblock %}
{% block script %}
<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
<script>
$(function () {
        $('#assets_table').DataTable({
          "paging": true,       <!-- 允许分页 -->
          "lengthChange": true, <!-- 允许改变每页显示的行数 -->
          "searching": true,    <!-- 允许内容搜索 -->
          "ordering": true,     <!-- 允许排序 -->
          "info": true,         <!-- 显示信息 -->
          "autoWidth": false    <!-- 固定宽度 -->
        });
      });

</script>
{% endblock %}

baseline/templates/baseline/show.html
{% extends 'base.html'%}
{% load static%}

{% block title %}上传文件数据{% endblock %}
{% block css %}
     <link rel="stylesheet" href="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
{% endblock %}
{% block content %}
{% csrf_token %}
this is a test
{{ test }}
{% endblock %}
{% block script %}
<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
{% endblock %}

baseline/templates/baseline/windows_vuln_check_res_display.html
{% extends 'base_JC.html'%}
{% load static%}
{% load base64_jc %}

{% block title %}基线检查记录{% endblock %}
{% block css %}
     <link rel="stylesheet" href="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
<style>
.jc-red-badge{
  display: inline-block;
    min-width: 10px;
    padding: 3px 7px;
    font-size: 12px;
    font-weight: 700;
    line-height: 1;
    color: #fff;
    text-align: center;
    white-space: nowrap;
    vertical-align: middle !important;
    background-color:red;
    border-radius: 10px;
}
/* td{
  word-break:break-all;
  vertical-align: middle!important;
} */
table{
	table-layout:fixed;
}	
td{
    overflow:hidden;
    white-space:nowrap;
    text-overflow:ellipsis;
}
</style>
{% endblock %}
{% block content %}
   <!-- Main content -->
   <section class="content">

     <!-- 检查结果 -->
       <div class="box">
         <div class="box-header">
           <h3 class="box-title">检查结果</h3>
         </div>
         <div class="box-body">
          <table id="exp_table" class="table table-bordered table-striped dataTable">
            <thead>
              <tr>
                <th style="width:30%">name</th>
                <th style="width:20%">KB</th>
                <th style="width:20%">CVE</th>
                <th style="width:20%">CVE-info</th>
              </tr>
            </thead>
            <tbody>
              {% for checkResDict in vulnCheckResList%}
                  
              <tr>
                <td>{{checkResDict.name}}</td>
                <td>KB{{checkResDict.KBName}}</td>
                <td>{{checkResDict.CVEName}}</td>
                <td>{{checkResDict.impact}}</td>
              </tr>
              {% endfor%}
            </tbody>
          </table>
        </div>
       </div>
   </section>
{% endblock %}
{% block script %}
<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
<script>
$(function () {
        $('#exp_table').DataTable({
          "paging": true,       <!-- 允许分页 -->
          "lengthChange": true, <!-- 允许改变每页显示的行数 -->
          "searching": true,    <!-- 允许内容搜索 -->
          "ordering": true,     <!-- 允许排序 -->
          "info": true,         <!-- 显示信息 -->
          "autoWidth": false    <!-- 固定宽度 -->
        });
      });

</script>
{% endblock %}